### ISSUE TITLE
Feature Request: 6-digit counts for kills/items/secrets.

### ISSUE THREAD

**Issue by Shockwave508** [FelesNoctis/HXRTCHUD_Platinum#2]
Is it possible to go even further with the kills/items/secrets display, to display six digits for each, for the eventuality that there are absurd counts of each?

Example below

K:######-######
I:######-######
S:######-######

This would be operated by the same CVAR that swaps between 4-digit and 5-digit displays.

**Comment by FelesNoctis** [comment]
Yeah, I don't see why not. Might have to reduce the text to K/I/S, but we'll see what happens.

**Comment by FelesNoctis** [comment]
Added in https://github.com/FelesNoctis/HXRTCHUD_Platinum/commit/04154b721d5dc530db2727d5a383f4f7c659b0fe
