### ISSUE TITLE
Feature Request: Support for Ac!d's Eriguns

### ISSUE THREAD

**Issue by Shockwave508** [FelesNoctis/HXRTCHUD_Platinum#3]
Attached is an analysis list for all weapons, powerups, and munitions for Ac!d's Eriguns. 
Mod can be found here: https://forum.zdoom.org/viewtopic.php?t=65535

[Acids_Eriguns.txt](https://github.com/FelesNoctis/HXRTCHUD_Platinum/files/9486364/Acids_Eriguns.txt)

**Comment by FelesNoctis** [comment]
Functionality is complete as of https://github.com/FelesNoctis/HXRTCHUD_Platinum/commit/e9f9fb0862f8c5909c641b13ec9a8423bb644dbd

Still have a few icons to make. Will also have to write a ZScript handler in the future to handle the grenade/mine Launcher swap and the heat buildup of the Nailgun. You know, once I know ZScript.

**Comment by FelesNoctis** [comment]
Icons and reactive element integration complete as of https://github.com/FelesNoctis/HXRTCHUD_Platinum/commit/7f757a04d7822c752f62e4c1f3c64ad3b45dc005

ZScript-required handling will come at a later date.
